In [2]:
#1. Create a null array of size 10 but the fifth value which is 1

# Importing Numpy
import numpy as np
myarray=np.array([None,None,None,None,1,None,None,None,None,None])
print(myarray)


#OR TRY THIS
a=np.array([None]*10, dtype=object)
a[4]=1
print(a)

[None None None None 1 None None None None None]
[None None None None 1 None None None None None]


In [22]:
#2. Reverse a above created array (first element becomes last)
myarray2=myarray[::-1]
print(myarray2)
print ('1D array in numpy is %s\n'%myarray2)
print ('shape of the numpy array is %s\n'%myarray2.shape)

[None None None None None 1 None None None None]
1D array in numpy is [None None None None None 1 None None None None]

shape of the numpy array is 10



In [21]:
#3. Create a 3x3 matrix with values ranging from 0 to 8
mymatrix = [[0,1,2],[3,4,5],[6,7,8]]
m=np.array(mymatrix)
print(m)
print(m.shape)
print ('Flattened version of numpy matrix is %s\n'% m.flatten())

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(3, 3)
Flattened version of numpy matrix is [0 1 2 3 4 5 6 7 8]



In [47]:
#4. Find indices of non-zero elements from [1,2,0,0,4,0]
array4=np.array([1,2,0,0,4,0])
arraynotzero=np.where(array4 != 0)
print ('Elements that are non-zero are %s'%arraynotzero)

Elements that are non-zero are [0 1 4]


In [34]:
#5. Create a 3x3x3 array with random values
array5=np.random.uniform(0,1,size=(3,3,3))
print ('matrix generated from numpy.random.uniform is \n%s\n'%array5)

matrix generated from numpy.random.uniform is 
[[[0.91161363 0.88992668 0.79462594]
  [0.45023735 0.50855014 0.79382301]
  [0.15221636 0.59379919 0.90154426]]

 [[0.53705815 0.15637561 0.85194738]
  [0.1405966  0.34286599 0.47209046]
  [0.9362961  0.24328514 0.20874084]]

 [[0.23994202 0.3414457  0.18791452]
  [0.57353168 0.33176356 0.78929838]
  [0.31301794 0.416955   0.06796209]]]



In [68]:
#6. Create a 10x10 array with random values and find the minimum and maximum values
array6 = np.random.randint(0,10,(10,10))
print ('10x10 matrix is \n%s\n'%array6)
min=array6.min()
#or min=np.min(array6)
max=array6.max()
#or max=np.max(array6)
print ('minimum value is \n%s\n'%min)
print ('maximum value is \n%s\n'%max)

10x10 matrix is 
[[9 8 1 6 4 3 8 7 5 4]
 [3 1 9 8 5 7 6 1 5 5]
 [3 3 0 1 5 2 6 1 2 6]
 [5 8 5 4 6 8 1 3 9 5]
 [0 3 5 6 7 5 7 1 6 1]
 [2 6 4 2 1 5 6 9 0 2]
 [8 9 7 7 6 3 2 4 6 8]
 [6 6 0 8 6 2 1 8 9 6]
 [1 5 0 9 8 6 8 8 2 1]
 [6 7 7 9 7 0 2 0 1 8]]

minimum value is 
0

maximum value is 
9



In [74]:
#7. Create a random vector of size 30 and find the mean value
array7=np.random.randint(0,100,(1,30))
print ('vector is \n%s\n'%array7)
mean7=array7.mean()
#or mean7=np.mean(array7)
print('vector mean is \n%s\n'%mean7)

vector is 
[[65 99 10  8  9 28 18 59 81 19 33 56 60 12 22  9 55  8 97 27 13 53 46 68
  44 34 36 58  5 42]]

vector mean is 
39.13333333333333



In [6]:
#8. Create a 2d array with 1 on the border and 0 inside
import numpy as np
row1=np.ones((1,10))
row2=[(1,0,0,0,0,0,0,0,0,1)]
newarray=np.vstack([row1,row2,row2,row2,row1])
print('The resulting appended vector is \n%s\n'%newarray)

#another option
array8=np.ones((7,7))
print(array8)
array8[1:-1,1:-1]=0
print(array8)

The resulting appended vector is 
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [7]:
#9. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
array9_1=np.random.randint(0,10,size=(5,3))
print('The 5x3 matrix is \n%s\n'%array9_1)
array9_2=np.random.randint(0,10,size=(3,2))
print('The 3x2 matrix is \n%s\n'%array9_2)
array9=array9_1 @ array9_2
print('The resulting matrix product is \n%s\n'%array9)

#or
array9=np.dot(array9_1,array9_2)

The 5x3 matrix is 
[[2 1 2]
 [2 6 1]
 [3 1 7]
 [5 8 9]
 [0 6 8]]

The 3x2 matrix is 
[[8 7]
 [1 2]
 [7 1]]

The resulting matrix product is 
[[ 31  18]
 [ 29  27]
 [ 74  30]
 [111  60]
 [ 62  20]]



In [9]:
#10. Extract the integer part of a random array
array10=np.random.uniform(-10,10,size=(1,10))
print(array10)
array10trunc=np.trunc(array10)
print('The resulting matrix is \n%s\n'%array10trunc)
#or
array10trunc=np.rint(array10)
print(array10trunc)


[[ 0.57316042  7.06351181 -5.21709314  1.11824255  5.73034754  6.32308131
  -7.29272984  9.32871119 -7.18143878  2.77766167]]
The resulting matrix is 
[[ 0.  7. -5.  1.  5.  6. -7.  9. -7.  2.]]

[[ 1.  7. -5.  1.  6.  6. -7.  9. -7.  3.]]


In [43]:
#11. Create a 5x5 matrix with row values ranging from 0 to 4
array11=np.random.randint(0,5,size=(5,5))
print('The 5x5 matrix with random whole numbers from 0 to 4 is \n%s\n'%array11)

The 5x5 matrix with random whole numbers from 0 to 4 is 
[[3 1 2 0 0]
 [3 0 2 0 1]
 [1 1 2 1 4]
 [4 3 4 2 4]
 [1 1 1 0 3]]



In [59]:
#12.  Create a random vector of size 10 and sort it
array12=np.random.randint(0,10,size=(1,10))
print('The random vector of size 10 is \n%s\n'%array12)
array12.sort()
print('The random vector of size 10 SORTED is \n%s\n'%array12)

The random vector of size 10 is 
[[9 2 3 5 2 9 6 2 5 3]]

The random vector of size 10 SORTED is 
[[2 2 2 3 3 5 5 6 9 9]]



In [11]:
#13. Consider two random array A anb B, check if they are equal.
array13_1=np.random.randint(0,10,size=(1,10))
array13_2=np.random.randint(0,10,size=(1,10))
print('The first random array is \n%s\n'%array13_1)
print('The second random array is \n%s\n'%array13_2)
SAME=np.array_equal(array13_1, array13_2, equal_nan=False)   #for integers
print('Are they equal: \n%s\n'%SAME)

option1=np.allclose(array13_1,array13_2)   #for floats
print(option1)

The first random array is 
[[7 2 4 1 5 1 0 1 7 4]]

The second random array is 
[[3 0 6 8 7 1 2 9 1 9]]

Are they equal: 
False

False


In [37]:
#14. How to tell if a given 2D array has null columns?
import numpy as np
array14_1 = np.random.randint(0,3,(3,10)).astype(float)
print('The original random array is \n%s\n'%array14_1)
array14_1[:,3] = np.nan
print('The array with some NaN values is \n%s\n'%array14_1)
NaNCheck = np.isnan(array14_1)
print('The check of NaN values is \n%s\n'%((NaNCheck.all(axis=0)).any()))

The original random array is 
[[0. 1. 1. 1. 0. 2. 1. 0. 0. 0.]
 [1. 1. 1. 1. 1. 2. 1. 0. 2. 0.]
 [0. 2. 1. 0. 0. 0. 0. 1. 2. 1.]]

The array with some NaN values is 
[[ 0.  1.  1. nan  0.  2.  1.  0.  0.  0.]
 [ 1.  1.  1. nan  1.  2.  1.  0.  2.  0.]
 [ 0.  2.  1. nan  0.  0.  0.  1.  2.  1.]]

The check of NaN values is 
True



In [60]:
#15. Considering a four dimensions array, how to get sum over the last two axis at once?
array15 = np.random.randint(0,10,(3,4,3,4))
print('The 4D array is \n%s\n'%array15)
sum_2axis = array15.sum(axis=(-1,-2))
print('The sum of the last two axes is \n%s\n'%sum_2axis)

The 4D array is 
[[[[3 0 8 5]
   [2 5 8 5]
   [5 3 4 1]]

  [[2 3 5 4]
   [9 3 7 9]
   [2 5 9 8]]

  [[9 1 7 2]
   [8 5 4 7]
   [0 5 0 3]]

  [[6 7 6 5]
   [4 8 7 7]
   [6 3 7 7]]]


 [[[1 9 9 5]
   [2 5 8 1]
   [5 3 2 4]]

  [[7 1 0 4]
   [7 1 3 8]
   [3 3 7 6]]

  [[4 6 1 8]
   [0 3 8 4]
   [7 1 6 1]]

  [[9 8 4 6]
   [1 8 3 3]
   [2 2 3 2]]]


 [[[1 6 9 5]
   [6 1 9 2]
   [1 3 3 7]]

  [[8 8 2 6]
   [8 5 5 5]
   [3 1 4 9]]

  [[8 7 1 9]
   [3 1 2 1]
   [3 5 8 7]]

  [[7 1 3 8]
   [0 6 2 9]
   [0 6 7 7]]]]

The sum of the last two axes is 
[[49 66 51 73]
 [54 50 49 51]
 [53 64 55 56]]

[[49 66 51 73]
 [54 50 49 51]
 [53 64 55 56]]


In [12]:
#16. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?
#Question: I'm not sure if this is right. I tried different things, but taking the outer product of
#arrays with non-equal dimensions seems to work. I did not find a solution in the videos or in the notebook, so
#I tried to find something online.
array16_1 = np.ones((5,5,3))
print('The 5x5x3 matrix is \n%s\n'%array16_1)
array16_2 = 2*np.ones((5,5))
print('The 5x5 array is \n%s\n'%array16_2)
finalarray=(array16_1 * array16_2[:,:,None])
print('The final array is \n%s\n'%finalarray)


#also outer
finalarray2=np.outer(array16_1,array16_2)
print(finalarray2)

The 5x5x3 matrix is 
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]

The 5x5 array is 
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]

The final array is 
[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]

[[2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 ...
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]]


In [104]:
#17. Extract all the contiguous 3x3 blocks from a random 10x10 matrix
#CONFUSED: Outside of my understanding from the lectures. Sorry. I can make the matrix but not sure how 
#to get the 'blocks'
array17=np.random.randint(0,10,size=(10,10))
print(array17)
#here I grab the 3x3 matrices without overlap starting in row1, col1
    array17_1=array17[0:3,0:3]
    array17_2=array17[0:3,3:6]
    array17_3=array17[0:3,6:9]
    array17_4=array17[3:6,0:3]
    array17_5=array17[3:6,3:6]
    array17_6=array17[3:6,6:9]
    array17_7=array17[6:9,0:3]
    array17_8=array17[6:9,3:6]
    array17_9=array17[6:9,6:9]
print(array17_1)
print(array17_2)
print(array17_3)
print(array17_4)
print(array17_5)
print(array17_6)
print(array17_7)
print(array17_8)
print(array17_9)

#try this
#def contiguous_3x3_blocks(a):
 #   m, n =a.shape
  #  return [a[i:i=3,j:j+3]]


[[9 5 9 3 5 8 7 3 4 7]
 [0 0 0 6 3 7 3 9 6 9]
 [1 8 7 3 3 7 5 0 5 6]
 [8 3 5 0 5 7 0 9 5 5]
 [2 4 0 1 6 5 4 0 9 4]
 [7 1 5 2 2 5 3 2 6 6]
 [8 2 6 3 2 3 1 6 2 2]
 [6 8 8 1 6 4 7 8 4 3]
 [1 5 7 9 0 2 7 0 2 8]
 [5 8 3 8 4 4 1 5 0 1]]
[[9 5 9]
 [0 0 0]
 [1 8 7]]
[[3 5 8]
 [6 3 7]
 [3 3 7]]
[[7 3 4]
 [3 9 6]
 [5 0 5]]
[[8 3 5]
 [2 4 0]
 [7 1 5]]
[[0 5 7]
 [1 6 5]
 [2 2 5]]
[[0 9 5]
 [4 0 9]
 [3 2 6]]
[[8 2 6]
 [6 8 8]
 [1 5 7]]
[[3 2 3]
 [1 6 4]
 [9 0 2]]
[[1 6 2]
 [7 8 4]
 [7 0 2]]


In [121]:
#18. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?
array18 = np.ones((16,16))
print(array18)
blocksize=4
# we want to grab 4x4 chunks and sum them (should be 16)
block4_4 = np.add.reduceat(np.add.reduceat(array18, np.arange(0, array18.shape[0], blocksize), axis=0),
                                       np.arange(0, array18.shape[1], blocksize), axis=1)
print('The block sum is \n%s\n'%block4_4)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
The block sum is 
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]



In [119]:
#19. Generate 2 random gaussian distributions and run a t-test to see differences
# one distribution is mean=0, sd=1 and size 100; second is mean 0.5, sd=1 and size=30. We run an independent t-test
array19_1 = np.random.normal(0, 1, size=100)
array19_2 = np.random.normal(0.5, 1, size=50)

stats.ttest_ind(array19_1, array19_2)   



Ttest_indResult(statistic=-2.575462467672561, pvalue=0.01099044151906726)

In [23]:
#EXTRA - calculate summary stats using a dataset in a csv

import pandas as pd
import numpy as np

df = pd.read_csv (r'sample_test_data.csv')
print ('-------------------------------------\n')          
print ('Mean of item1 is \n%s\n'%np.mean(df.item1))
print ('SD of item1 is %s\n'%np.std(df.item1))
print ('Minimum of item1 is %s\n'%np.min(df.item1))
print ('Maximum of item1 is %s\n'%np.max(df.item1))
print ('Q10 of item1 is %s\n'%(str(np.percentile(df.item1,10))))
print ('Q50 of item1 is %s\n'%(str(np.percentile(df.item1,50))))
print ('Q90 of item1 is %s\n'%(str(np.percentile(df.item1,90))))

print ('-------------------------------------\n')          
print ('Mean of item2 is \n%s\n'%np.mean(df.item2))
print ('SD of item2 is %s\n'%np.std(df.item2))
print ('Minimum of item2 is %s\n'%np.min(df.item2))
print ('Maximum of item2 is %s\n'%np.max(df.item2))
print ('Q10 of item2 is %s\n'%(str(np.percentile(df.item2,10))))
print ('Q50 of item2 is %s\n'%(str(np.percentile(df.item2,50))))
print ('Q90 of item2 is %s\n'%(str(np.percentile(df.item2,90))))

print ('-------------------------------------\n')          
print ('Mean of item3 is \n%s\n'%np.mean(df.item3))
print ('SD of item3 is %s\n'%np.std(df.item3))
print ('Minimum of item3 is %s\n'%np.min(df.item3))
print ('Maximum of item3 is %s\n'%np.max(df.item3))
print ('Q10 of item3 is %s\n'%(str(np.percentile(df.item3,10))))
print ('Q50 of item3 is %s\n'%(str(np.percentile(df.item3,50))))
print ('Q90 of item3 is %s\n'%(str(np.percentile(df.item3,90))))

#and so on


-------------------------------------

Mean of item1 is 
0.6407563025210085

SD of item1 is 0.47977876495382177

Minimum of item1 is 0

Maximum of item1 is 1

Q10 of item1 is 0.0

Q50 of item1 is 1.0

Q90 of item1 is 1.0

-------------------------------------

Mean of item2 is 
0.6176470588235294

SD of item2 is 0.4859621071134817

Minimum of item2 is 0

Maximum of item2 is 1

Q10 of item2 is 0.0

Q50 of item2 is 1.0

Q90 of item2 is 1.0

-------------------------------------

Mean of item3 is 
1.6785714285714286

SD of item3 is 0.4670248868079298

Minimum of item3 is 1

Maximum of item3 is 2

Q10 of item3 is 1.0

Q50 of item3 is 2.0

Q90 of item3 is 2.0

